import '../styles/globals.css';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  return(
    <>
    <Head>
        <title>Pizza Trio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Trio.jpg" />
      </Head>
    <Navbar/>
     <Component {...pageProps} />
  <Footer/>
  </>
  )
}

export default MyApp
